name: "Build"
on:
  [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        cd functions
        npm i
        npm run build
        npm run lint
        # npm test
